name: multilingual_chat
description: Chat with an AI bot in different languages.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  sqflite: ^2.0.0
  fluttertoast: ^8.2.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  graphic: ^2.2.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/db/current.sql

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/OpenSans_Condensed-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans_Condensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans_Condensed-ExtraBoldItalic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
          style: italic
        - asset: assets/fonts/OpenSans_Condensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans_Condensed-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans_SemiCondensed-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/OpenSans_Condensed-LightItalic.ttf
          style: italic
        - asset: assets/fonts/OpenSans_SemiCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans_Condensed-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans_SemiCondensed-ExtraBoldItalic.ttf
          style: italic
        - asset: assets/fonts/OpenSans_Condensed-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/OpenSans_SemiCondensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans_Condensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans_SemiCondensed-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans_Condensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans_SemiCondensed-LightItalic.ttf
          style: italic
        - asset: assets/fonts/OpenSans_Condensed-SemiBoldItalic.ttf
          style: italic
        - asset: assets/fonts/OpenSans_SemiCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans_Condensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans_SemiCondensed-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
          style: italic
        - asset: assets/fonts/OpenSans_SemiCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans_SemiCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans_SemiCondensed-SemiBoldItalic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-LightItalic.ttf
          style: italic
        - asset: assets/fonts/OpenSans_SemiCondensed-SemiBold.ttf
          weight: 600

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
