import 'dart:math';

class TopicGeneratorService {
  static const topics = [
    "What's your favorite way to waste time?",
    "Disasters",
    "Do you care about fashion? What style of clothes do you usually wear?",
    "What's the best sitcom past or present?",
    "What old trend is coming back these days?",
    "Windmills",
    "What's the most underrated or overrated TV show?",
    "Parachuting",
    "Hippopotamus",
    "Basketball",
    "Do you usually achieve the goals you set? Why or why not?",
    "What kind of interior do you like a restaurant to have?",
    "Oil",
    "What is your favorite sports team?",
    "What is the strangest app you have heard of or tried?",
    "Which do you prefer, popular music or relatively unknown music?",
    "What was the best invention of the last 50 years?",
    "Napoleon",
    "Engineering",
    "Earthquake",
    "Fortune Tellers",
    "How often do you go to the library?",
    "Where and when was the most amazing sunset you have ever seen?",
    "Do you play in any fantasy sports leagues? If so, how into fantasy sports are you?",
    "Tennis",
    "What is your dream job?",
    "Lighthouses",
    "How often do you check your phone?",
    "Pipe Organs",
    "What's your favorite thing about our office?",
    "Bakeries",
    "What would you want your last meal to be if you were on death row?",
    "Shipwrecks",
    "What sports do you like to watch?",
    "What animal or insect do you wish humans could eradicate?",
    "What are you best at?",
    "Execution",
    "What do you do when you hang out with your friends?",
    "If your mind were an island, what would it look like?",
    "Typewriters",
    "What's the best way to discover new music?",
    "Has anyone ever saved your life?",
    "Dance",
    "What was your favorite children's book?",
    "What is the best way to stay motivated and complete goals?",
    "What is the most useful app on your phone?",
    "Sharks",
    "What do you bring with you everywhere you go?",
    "Smoking",
    "How has technology changed the music industry?",
    "Communism",
    "Archery",
    "What is your favorite piece of technology that you own?",
    "Seashells",
    "Who in your life brings you the most joy?",
    "What do you do for a living?",
    "If you could learn the answer to one question about your future, what would the question be?",
    "What are some good and bad things about the education system in your country?",
    "What do you fear is hiding in the dark?",
    "Fishing",
    "Gypsies",
    "Army",
    "What is the first think you notice about a guy or girl?",
    "What do you think of staycations? (Vacationing and seeing tourist attractions where you live.)",
    "What did you do on your last vacation?",
    "What is the best pair of shoes you have ever owned? Why were they so good?",
    "Where do you plan on going for your next vacation?",
    "Medicine",
    "Monkeys",
    "What movie scene choked you up the most?",
    "Cobblers",
    "Which is more important, having a great car or a great house? Why?",
    "Skull",
    "Do you like documentaries? Why / why not?",
    "Circus",
    "What are your goals for the next two years?",
    "What does your own personal hell look like? How about your own personal heaven?",
    "Do you have any pets?",
    "Crocodiles",
    "What technology from a science fiction movie would you most like to have?",
    "How do clothes change how the opposite sex views a person?",
    "Telephone",
    "Whatâ€™s your favorite way to waste time?",
    "Sports",
    "Swings",
    "What do you think of tour group packages?",
    "What do you do to get rid of stress?",
    "Do you wish there were more or fewer holidays? Why?",
    "Cocoa",
    "Which do you prefer? Books or movies?",
    "Are bigger or smaller schools better?",
    "How have TV shows changed over the years?",
    "What's the best thing about traveling? How about the worst thing?",
    "Paper Boys",
    "What are your plans for this weekend?",
    "What book has influenced you the most?",
    "Postcards",
    "What is your favorite day of the week?",
    "Toads",
    "If you had to get rid of a holiday, which would you get rid of? Why?",
    "Who would be the worst person to be stuck in an elevator with? How about the best person to be stuck in an elevator with?",
    "Laundry",
    "What's the best / worst thing about your work/school?",
    "What was the last thing you purchased?",
    "What do you like to do in the spring?",
    "Elephants",
    "What was your favorite restaurant when you were a child?",
    "What will the future of education be?",
    "Pigs",
    "Do you have any siblings?",
    "Are there any songs that always bring a tear to your eye?",
    "Where do you get your recommendations for what to do and where to stay when you travel?",
    "Alligators",
    "What is something you are obsessed with?",
    "Pottery",
    "What is your favorite movie soundtrack?",
    "What's the worst job interview you've ever had?",
    "Do you prefer traveling alone or with a group?",
    "Cactus",
    "What will be the future of TV shows?",
    "What's the most frustrating app you have tried?",
    "What foods do you absolutely hate?",
    "Railroads",
    "Turtles",
    "Balloons",
    "Journalism",
    "Did your family take seasonal vacations?",
    "Tobacco",
    "Shoes",
    "How can technology improve education? Can it hurt education?",
    "What sci-fi movie or book would you like the future to be like?",
    "What do you hope to achieve in your professional life?",
    "Where did you go on your last vacation?",
    "Astronomy",
    "What is the most comfortable piece of clothing you own?",
    "Hockey",
    "If you were in the Olympics, what sport would you play?",
    "What do app makers do that really annoys you?",
    "How can governments make education more efficient?",
    "Have your parents influenced what goals you have?",
    "What was the best period of your life so far? What do you think will be the best period of your entire life?",
    "What was the last song you listened to?",
    "If you could call up anyone in the world and have a one-hour conversation, who would you call?",
    "Canoes",
    "What restaurant do you eat at most?",
    "Do athletes deserve the high salaries they receive? Why or why not?",
    "Spa",
    "What is something that really annoys you but doesn't bother most people?",
    "Where is the best place to take a date?",
    "What bands or types of music do you listen to when you exercise?",
    "If you had 10 million dollars, would you still be working/going to school?",
    "Do you experience phantom vibration? (Feeling your phone vibrate even though it didn't.)",
    "Where is the nicest place you have been to in fall?",
    "Ostriches",
    "How often do you curse? And what's your go-to string of curse words?",
    "What was the last funny video you saw?",
    "Vegetables",
    "How often do you binge watch shows?",
    "Olympic Games",
    "If you opened a business, what kind of business would it be?",
    "Lions",
    "Sugar",
    "Muppets",
    "How have your goals changed over your life?",
    "How often do you stay up past 3 a.m.?",
    "Weaving",
    "If you didn't care at all what people thought of you, what clothes would you wear?",
    "Coins",
    "Americans",
    "What were you really into when you were a kid?",
    "Airports",
    "What book has changed one of your long-held opinions?",
    "Why do you think sports are common across almost all cultures present and past?",
    "Who do you think has the biggest impact on fashion trends: actors and actresses, musicians, fashion designers, or consumers?",
    "What is the most disgusting habit some people have?",
    "What song always puts you in a good mood?",
    "South America",
    "If you could write a book, would it be fiction or non-fiction?",
    "Sheep",
    "Boy Scouts",
    "Do you play any sports?",
    "Magicians",
    "How often do you exercise?",
    "Beekeeping",
    "What is the longest plane trip you have taken?",
    "If you were a king/queen, what would your throne look like?",
    "What's the most useful thing you own?",
    "Artists",
    "Boxing",
    "What is the silliest fear you have?",
    "Snakes",
    "Wood",
    "Potatoes",
    "Do you think people read more or fewer books now than 50 years ago?",
    "Coffin",
    "Salt",
    "If you opened a restaurant, what kind of food would you serve?",
    "Wrestling",
    "Who was the first band or musician you were really into? Do you still like them?",
    "If you were a book, what would the title be?",
    "Fencing",
    "Africa",
    "Ferry Boats",
    "What was the most overhyped place you've traveled to?",
    "What did you do this past weekend?",
    "Politics",
    "Cotton",
    "What flavor of ice cream do you wish existed?",
    "Zebras",
    "What do you do to improve your mood when you are in a bad mood?",
    "You have to relive one day of your life forever. Which day do you choose?",
    "What was the worst book you had to read for school? How about the best book you had to read for school?",
    "What are some goals you have already achieved?",
    "Coal",
    "Diving",
    "What is the biggest holiday for your family?",
    "Records, tapes, CDs, MP3s, streaming. Which did you grow up with? What is good and bad about each?",
    "Horses",
    "Whales",
    "Does technology simplify life or make it more complicated?",
    "What holidays have been over-commercialized?",
    "Cheese",
    "What's the worst fast food restaurant?",
    "What do you think of buffets?",
    "What was (is) your least favorite subject?",
    "Do you believe in soul mates?",
    "What's the best way to travel? (Plane, car, train, etc.)",
    "Would you eat at a restaurant that was really dirty if the food was amazing?",
    "What type of phone do you have?",
    "If you had a personal mascot, what would your mascot be?",
    "What do you think of homeschooling?",
    "Matches",
    "Hammocks",
    "What three words best describe you?",
    "What are the three best apps on your phone?",
    "What would be your perfect weekend?",
    "Seesaws",
    "Accordions",
    "Was there ever an event in your life that defied explanation?",
    "What is the strangest dream you have ever had?",
    "Do you text more or call more? Why?",
    "Water Skiing",
    "Games",
    "Mining",
    "Which season are you most active in?",
    "Donkeys",
    "How do you feel if you accidentally leave your phone at home?",
    "Birds",
    "Does having a day off for a holiday increase or decrease productivity at work?",
    "What three words best describe you?",
    "Apes",
    "Where was the last place you went on vacation?",
    "What is the fanciest restaurant you have eaten at?",
    "World War 1",
    "What's your favorite way to decompress from a long day at work?",
    "How should success be measured? And by that measurement, who is the most successful person you know?",
    "Camels",
    "Gold",
    "Do you prefer physical books or ebooks?",
    "Who is your favorite athlete?",
    "If you could meet anyone in history, who would it be?",
    "What is one thing you miss about being a kid?",
    "Europe",
    "Where is the most beautiful place near where you live?",
    "What is the most annoying habit someone can have?",
    "Mountaineering",
    "How much do you plan for the future?",
    "Radiology",
    "Would you rather be rich and never find true love or be poor and find true love?",
    "Post Office",
    "Sailing",
    "Do you like horror movies? Why or why not?",
    "Do you like classical music?",
    "What or who has taught you most of the information you use regularly?",
    "What's the best pet name you can come up with for a specific type of pet? (Like theseÂ orange cat names.)",
    "Puppets",
    "Drugstores",
    "What problems will technology solve in the next 5 years? What problems will it create?",
    "Athletics",
    "What book genres do you like to read?",
    "Who are the 3 greatest athletes of all time?",
    "Who is someone popular now that you really like? Why do you like them so much?",
    "What's your favorite number? Why?",
    "What type of kid were you (e.g. spoiled, rebellious, well-behaved, quiet, obnoxious...)?",
    "What was your least favorite job that you've ever had?",
    "What food do you know you shouldn't eat but can't stop yourself?",
    "Rice",
    "Playing Cards",
    "Do you always have to have the latest phone?",
    "Where is the most awe-inspiring place you have been?",
    "Rhinoceros",
    "Where did you go last weekend? / What did you do last weekend?",
    "What was your worst vacation experience?",
    "What do you do when you're bored?",
    "Jewelry",
    "What is a controversial opinion you have?",
    "Farmers Markets",
    "Cemetery",
    "What do you think of online education?",
    "Which emerging technology are you most excited about?",
    "Marionettes",
    "Radio",
    "Do you prefer short hair or long hair on a guy/girl?",
    "Music",
    "What are some goals you have failed to accomplish?",
    "Red Cross",
    "What was your first smartphone? How did you feel when you got it?",
    "Firemen",
    "What personal goals do you have?",
    "If you could have any animal as a pet, what animal would you choose?",
    "Have you ever saved an animal's life? How about a person's life?",
    "Airplanes",
    "Spinning",
    "Central America",
    "What are some strange beliefs that some people have?",
    "Veterinarians",
    "Motherhood",
    "Royalty",
    "Justice",
    "What do you think of standardized tests?",
    "Crime",
    "Sewing Machines",
    "Spiritism",
    "Volleyball",
    "Which TV show do you want your life to be like?",
    "Where is the worst place you have been stuck for a long time?",
    "What piece of technology would look like magic or a miracle to people in medieval Europe?",
    "What do you know about the history of some holidays?",
    "Do you prefer fiction or nonfiction books?",
    "What did you want to grow up to be when you were younger?",
    "Clowns",
    "What's your favorite way to get exercise?",
    "Amusement Parks",
    "Bohemians",
    "Do you play any instruments?",
    "How much time do you spend watching sports in a week?",
    "If you could have a conversation with any famous person, who would it be?",
    "Dogs",
    "Which app has helped society the most? Which one has hurt society the most?",
    "Is it better to live where there are four seasons or where one season takes up most of the year?",
    "What is your favorite shirt?",
    "Cards",
    "What was the last book you read?",
    "What's your favorite genre of movie?",
    "What's your favorite movie? And what is your favorite song?",
    "Carpentry",
    "Do you have any pets? What are their names?",
    "Banana",
    "When was the last time you had a food fight?",
    "What's your favorite outfit?",
    "If your life was a meal, what would kind of meal would it be?",
    "Where would you like to travel next?",
    "Pigeons",
    "Can you think of any technology that has only made the world worse? How about a piece of technology that has only made the world better?",
    "What are you going to do this weekend?",
    "What is your favorite cuisine or type of food?",
    "Cycling",
    "Which do you prefer, fall or spring?",
    "What weird or useless talent do you have?",
    "Which sport is the most exciting to watch? Which is the most boring to watch?",
    "What do you look for in a guy/girl?",
    "Mummies",
    "What's your favorite food?",
    "Do you prefer to watch movies in the theater or in the comfort of your own home?",
    "What is your favorite song of all time?",
    "Bats",
    "How do you think traveling to a lot of different countries changes a person?",
    "What is a fashion trend you are really glad went away?",
    "What are some things that you should not say during a job interview?",
    "What was the last movie you watched? How was it?",
    "Billiards",
    "The best piece of advice you've ever gotten was what?",
    "Do you play sports video games? Which ones? Is playing the video game or playing the sport more fun? Why?",
    "Meteorology",
    "What is something that you have gotten in trouble for at school/work?",
    "What's the most addictive mobile game you have played?",
    "Hunting",
    "Time freezes for everyone but you for one day. What do you do?",
    "If you could make a holiday, what would it be like? What traditions would it have? What would people eat on your holiday?",
    "Giants",
    "What do you think about game shows? Do you have a favorite one?",
    "WhichÂ recent news storyÂ is the most interesting?",
    "If you could live anywhere in the world, where would it be?",
    "Shipping",
    "Tanning",
    "What kind of case do you have for your phone? Why did you choose it?",
    "What's the first thing you do after school/work?",
    "If you had intro music, what song would it be? Why?",
    "Rugby",
    "Have you ever been in love?",
    "What was your favorite book as a child?",
    "Which app seemed like magic the first time you used it?",
    "Zeppelins",
    "What's the best thing to do on a cold winter day?",
    "Where do you spend most of your free time/day?",
    "Disney Movies",
    "If you could choose any two famous people to have lunch or dinner with, who would it be?",
    "Do you like spicy food? Why or why not? What is the spiciest thing you have ever eaten?",
    "What do you like to do in your spare time?",
    "The worst piece of advice you've ever gotten was what?",
    "Mules",
    "Gymnastics",
    "Are you very active, or do you prefer to just relax in your free time?",
    "Rabbits",
    "Diamond",
    "When do you want to retire? What do you want to do when you retire?",
    "Who was your best friend in elementary school?",
    "Blacksmiths",
    "Volcanoes",
    "What will phones be like in 10 years?",
    "Will technology save the human race or destroy it?",
    "Milk",
    "What is your middle name?",
    "Football",
    "What is something popular now that annoys you?",
    "Gorillas",
    "What do you think about reality TV? Why do you think it's so popular?",
    "What makes you nervous?",
    "Coffee",
    "Do movies have the same power as books to change the world?",
    "What's the best show currently on TV?",
    "Have you ever given a presentation in front of a large group of people? How did it go?",
    "What kinds of food do you usually eat on your favorite holiday?",
    "How much time do you spend on the internet? What do you usually do?",
    "Military",
    "When was the last time you worked incredibly hard?",
    "Do you prefer summer or winter activities?",
    "Who is your favorite entertainer (comedian, musician, actor, etc.)?",
    "Vanilla",
    "Goats",
    "North Africa",
    "What is the last thing you do before you go to sleep?",
    "Salvation Army",
    "Is teaching a skill that can be taught?",
    "What was the best birthday wish or gift you've ever received?",
    "Death",
    "Bears",
    "Native Americans",
    "What do you think of tattoos? Do you have any?",
    "What is the best room in your house? Why?",
    "Lighters",
    "Do you believe in love at first sight?",
    "Who had the biggest impact on the person you have become?",
    "Do you like reality TV shows? Why or why not? If so, which ones?",
    "What are your turn offs?",
    "What piece of technology is really frustrating to use?",
    "What are some things you want to accomplish before you die?",
    "What is the most embarrassing piece of clothing you own?",
    "If you had to change your name, what would your new name be?",
    "What is the craziest, most outrageous thing you want to achieve?",
    "What was the biggest thing you have ever won?",
    "What's your favorite season? Why?",
    "Caves",
    "What is your guilty pleasure?",
    "How has the education you received changed your life?",
    "What's the worst movie you have seen recently?",
    "What is the most overrated movie?",
    "What cartoons did you watch as a child?",
    "How do you plan to make the world a better place?",
    "Where did you grow up?",
    "Hurricanes",
    "What's the funniest TV series you have seen?",
    "Funerals",
    "Soccer",
    "What do you think the next big technological advance will be?",
    "What is your first childhood memory?",
    "What album would you listen to on repeat?",
    "If you could bring back one TV show that was canceled, which one would you bring back?",
    "If some of the lesser-known holidays were commercialized, what would the commercialization look like?",
    "An app mysteriously appears on your phone that does something amazing. What does it do?",
    "What's the most refreshing thing on a hot summer day?",
    "What do you wish your phone could do?",
    "Agriculture",
    "You find a remote that can rewind, fast forward, stop, and start time. What do you do with it?",
    "Dolphins",
    "Shovels",
    "Murderers",
    "Tattoos",
    "Were you the class clown or teacher's pet?",
    "What is the first thing you do when you wake up?",
    "What food looks disgusting but tastes delicious?",
    "Bridges",
    "What is the hardest sport to excel at?",
    "What was (is) your favorite subject?",
    "Foxes",
    "X-rays",
    "What smell brings back great memories?",
    "What word or saying from the past do you think should come back?",
    "What's your favorite game to play?",
    "What is the strangest themed restaurant you have heard of?",
    "Slavery",
    "A portal to another world opens in front of you. You don't know how long it will stay open or if you'll be able to get back after you go through. What do you do?",
    "Cats",
    "Newspapers",
    "Prisons",
    "Tigers",
    "Nurses",
    "What's your favorite way to start lunch conversations?",
    "Who is the funniest person you've met?",
    "What book has had the biggest effect on the modern world?",
    "How often do you help others? Who do you help? How do you help?",
    "Pilots",
    "What is the most disgusting thing you have heard happened at a restaurant?",
    "What benefit do you bring to the group when you hang out with friends?",
    "Where is the most relaxing place you have been?",
    "Where did (do) you go to school?",
    "What did you do on your most recent birthday?",
    "What is the worst restaurant you have ever eaten at?",
    "Buffaloes",
    "Cigarettes",
    "Who was the last person you called?",
    "What is your least favorite food?",
    "What do you get every time you go grocery shopping?",
    "Baseball",
    "Would you advise someone to attend a university now that you've completed your education?",
    "What is the most annoying thing about your phone?",
    "Vaccines",
    "Frogs",
    "Giraffes",
    "Do you like going to concerts? Why or why not? What was the last concert you went to?",
    "Books",
    "Bread",
    "Now that indie publishing has become easier, have books gotten better or worse?",
    "Stadiums",
    "Dentistry",
    "Boats",
    "Have you traveled to any different countries? Which ones?",
    "Cricket",
    "Does fashion help society in any way?",
    "Skating",
    "Movie Theaters",
    "Socialism",
    "Barbers",
    "What is the worst hotel you have stayed at? How about the best hotel?",
    "When you describe yourself to others, what words do you use?",
    "Buddhism",
    "What is your favorite thing to eat or drink in winter?",
    "Flood",
    "Who are some of your favorite athletes?",
    "Money",
    "Motorcycles",
    "What trends did you follow when you were younger?",
    "Pipes",
    "What is your favorite holiday?",
    "What countries have you traveled to?",
    "Submarines",
    "Does the government have a place in regulating food? To what extent should government regulate food?",
    "Are you a saver or a spender?",
    "How many apps do you have on your phone?",
    "Where is the most beautiful place you have been?",
    "Pork",
    "Police",
    "When was the last time you went to a movie theater?",
    "How fast do you read?",
    "Chess",
    "Do you prefer to go off the beaten path when you travel?",
    "What defines a sport? Is fishing a sport? How about video game tournaments?",
    "Hotels",
    "Criminals",
    "What is the longest book you've read?",
    "Cows",
    "Masonry",
    "Banking",
    "Leather",
    "Printing",
    "Are you a very organized person?",
    "Who is your oldest friend? Where did you meet them?",
    "Pineapple",
    "Breweries",
    "Golf",
    "The world has become infested with rabid dogs with the intelligence of a 5-year-old, where do you hole up to survive the â€œa-pup-calypseâ€?",
    "What do you like to do to relax?",
    "Do you know what your your name means?",
    "When people make mistakes about food (especially foreign food), do you feel the need to correct them? (i.e.Â sushi / sashimiÂ orÂ stromboli / calzone)",
    "What's the strangest movie you have ever seen?",
    "Carousels",
    "Insects",
    "What is your favorite holiday?",
    "What is the best job interview you've ever had?",
    "Shells",
    "Asia",
    "Pharmacy",
    "What're the best and worst things about the marketplace where you get your apps?",
    "What is your favorite thing to eat or drink in winter?",
    "Airplanes",
    "Whales",
    "What was your first smartphone? How did you feel when you got it?",
    "Fortune Tellers",
    "Mules",
    "What's your favorite movie? And what is your favorite song?",
    "Which sport is the most exciting to watch? Which is the most boring to watch?",
    "What is the last thing you do before you go to sleep?",
    "Veterinarians",
    "What is the worst restaurant you have ever eaten at?",
    "Spinning",
    "Seesaws",
    "What are you best at?",
    "What was the last thing you purchased?",
    "Pork",
    "Typewriters",
    "What is something that really annoys you but doesn't bother most people?",
    "The worst piece of advice you've ever gotten was what?",
    "Do you believe in soul mates?",
    "Was there ever an event in your life that defied explanation?",
    "Dentistry",
    "Hurricanes",
    "Do you prefer to go off the beaten path when you travel?",
    "Do you like going to concerts? Why or why not? What was the last concert you went to?",
    "Flood",
    "Mining",
    "Coffee",
    "What do you think about game shows? Do you have a favorite one?",
    "Hippopotamus",
    "What do you think of tour group packages?",
    "What's your favorite way to start lunch conversations?",
    "Medicine",
    "Have you traveled to any different countries? Which ones?",
    "Have you ever saved an animal's life? How about a person's life?",
    "Where do you plan on going for your next vacation?",
    "What do you think of tattoos? Do you have any?",
    "Shipping",
    "Soccer",
    "Paper Boys",
    "Communism",
    "Telephone",
    "What is one thing you miss about being a kid?",
    "The best piece of advice you've ever gotten was what?",
    "If you could live anywhere in the world, where would it be?",
    "Foxes",
    "Engineering",
    "Sheep",
    "What do you like to do in your spare time?",
    "Do you like horror movies? Why or why not?",
    "Dogs",
    "What is a fashion trend you are really glad went away?",
    "Leather",
    "What do you get every time you go grocery shopping?",
    "Do you care about fashion? What style of clothes do you usually wear?",
    "Cotton",
    "If you could choose any two famous people to have lunch or dinner with, who would it be?",
    "Laundry",
    "What's your favorite game to play?",
    "Submarines",
    "What was your least favorite job that you've ever had?",
    "Who are the 3 greatest athletes of all time?",
    "Carpentry",
    "An app mysteriously appears on your phone that does something amazing. What does it do?",
    "Tigers",
    "What did you do on your most recent birthday?",
    "What is your dream job?",
    "What's the strangest movie you have ever seen?",
    "What was the last song you listened to?",
    "Execution",
    "Who are some of your favorite athletes?",
    "Where would you like to travel next?",
    "If you could write a book, would it be fiction or non-fiction?",
    "Time freezes for everyone but you for one day. What do you do?",
    "Buffaloes",
    "What cartoons did you watch as a child?",
    "What do app makers do that really annoys you?",
    "If you could call up anyone in the world and have a one-hour conversation, who would you call?",
    "How often do you go to the library?",
    "What type of phone do you have?",
    "Printing",
    "What is a controversial opinion you have?",
    "Journalism",
    "What kind of interior do you like a restaurant to have?",
    "What is the biggest holiday for your family?",
    "Military",
    "Which app seemed like magic the first time you used it?",
    "Criminals",
    "Movie Theaters",
    "World War 1",
    "Rugby",
    "Marionettes",
    "What do you do to improve your mood when you are in a bad mood?",
    "Clowns",
    "What was the last movie you watched? How was it?",
    "Goats",
    "Volleyball",
    "What's your favorite outfit?",
    "Amusement Parks",
    "Airports",
    "What do you look for in a guy/girl?",
    "Wrestling",
    "What sci-fi movie or book would you like the future to be like?",
    "Seashells",
    "How often do you binge watch shows?",
    "Ferry Boats",
    "What three words best describe you?",
    "Radiology",
    "Smoking",
    "If you had a personal mascot, what would your mascot be?",
    "What is your favorite piece of technology that you own?",
    "How much do you plan for the future?",
    "What is your guilty pleasure?",
    "Lions",
    "Ostriches",
    "Where is the most beautiful place you have been?",
    "Banking",
    "What personal goals do you have?",
    "Politics",
    "Do you believe in love at first sight?",
    "Are you a saver or a spender?",
    "Who in your life brings you the most joy?",
    "Shoes",
    "Coal",
    "What are your plans for this weekend?",
    "Tanning",
    "Who would be the worst person to be stuck in an elevator with? How about the best person to be stuck in an elevator with?",
    "When was the last time you went to a movie theater?",
    "Dolphins",
    "What or who has taught you most of the information you use regularly?",
    "X-rays",
    "Gorillas",
    "What is the best way to stay motivated and complete goals?",
    "What do you think of staycations? (Vacationing and seeing tourist attractions where you live.)",
    "When do you want to retire? What do you want to do when you retire?",
    "Diamond",
    "Africa",
    "Radio",
    "Bohemians",
    "Accordions",
    "Agriculture",
    "Cactus",
    "What was the biggest thing you have ever won?",
    "What're the best and worst things about the marketplace where you get your apps?",
    "Rabbits",
    "If you had to get rid of a holiday, which would you get rid of? Why?",
    "What foods do you absolutely hate?",
    "What trends did you follow when you were younger?",
    "Do you prefer physical books or ebooks?",
    "What type of kid were you (e.g. spoiled, rebellious, well-behaved, quiet, obnoxious...)?",
    "How much time do you spend watching sports in a week?",
    "What's the best way to travel? (Plane, car, train, etc.)",
    "Pigeons",
    "What is the hardest sport to excel at?",
    "What weird or useless talent do you have?",
    "Post Office",
    "Football",
    "Lighters",
    "Are there any songs that always bring a tear to your eye?",
    "Crime",
    "What is your favorite sports team?",
    "Barbers",
    "Giants",
    "What book genres do you like to read?",
    "Cards",
    "Parachuting",
    "Where do you get your recommendations for what to do and where to stay when you travel?",
    "Salt",
    "What do you like to do to relax?",
    "What did you want to grow up to be when you were younger?",
    "How often do you check your phone?",
    "What was your favorite children's book?",
    "Motorcycles",
    "What's the most underrated or overrated TV show?",
    "Hotels",
    "You find a remote that can rewind, fast forward, stop, and start time. What do you do with it?",
    "What are some good and bad things about the education system in your country?",
    "Newspapers",
    "What word or saying from the past do you think should come back?",
    "Who is your favorite athlete?",
    "Artists",
    "Swings",
    "What's the most useful thing you own?",
    "What will phones be like in 10 years?",
    "How much time do you spend on the internet? What do you usually do?",
    "Spa",
    "What is something you are obsessed with?",
    "How often do you stay up past 3 a.m.?",
    "Horses",
    "Europe",
    "What are you going to do this weekend?",
    "Do you play sports video games? Which ones? Is playing the video game or playing the sport more fun? Why?",
    "What piece of technology would look like magic or a miracle to people in medieval Europe?",
    "What's the best thing about traveling? How about the worst thing?",
    "What do you do to get rid of stress?",
    "What restaurant do you eat at most?",
    "If you could have a conversation with any famous person, who would it be?",
    "Does technology simplify life or make it more complicated?",
    "Is teaching a skill that can be taught?",
    "South America",
    "Shovels",
    "Does the government have a place in regulating food? To what extent should government regulate food?",
    "What is the most comfortable piece of clothing you own?",
    "What was the worst book you had to read for school? How about the best book you had to read for school?",
    "How fast do you read?",
    "What's the best thing to do on a cold winter day?",
    "Nurses",
    "Volcanoes",
    "Astronomy",
    "Circus",
    "North Africa",
    "What will the future of education be?",
    "Where did you go last weekend? / What did you do last weekend?",
    "When was the last time you had a food fight?",
    "If you opened a business, what kind of business would it be?",
    "Diving",
    "Do you like spicy food? Why or why not? What is the spiciest thing you have ever eaten?",
    "Weaving",
    "Do you play any sports?",
    "Justice",
    "What was your favorite book as a child?",
    "What are your goals for the next two years?",
    "Monkeys",
    "How can technology improve education? Can it hurt education?",
    "Now that indie publishing has become easier, have books gotten better or worse?",
    "Have you ever given a presentation in front of a large group of people? How did it go?",
    "What's your favorite number? Why?",
    "Coins",
    "How do clothes change how the opposite sex views a person?",
    "Do you experience phantom vibration? (Feeling your phone vibrate even though it didn't.)",
    "What will be the future of TV shows?",
    "What was the best birthday wish or gift you've ever received?",
    "Americans",
    "Postcards",
    "Where did (do) you go to school?",
    "What is the best room in your house? Why?",
    "Where is the best place to take a date?",
    "What's the most frustrating app you have tried?",
    "Cycling",
    "Who was the first band or musician you were really into? Do you still like them?",
    "Coffin",
    "Carousels",
    "Shipwrecks",
    "How do you feel if you accidentally leave your phone at home?",
    "Drugstores",
    "If your mind were an island, what would it look like?",
    "Potatoes",
    "Where did you grow up?",
    "What is the best restaurant in your area?",
    "What do you bring with you everywhere you go?",
    "What do you think of homeschooling?",
    "Who is your oldest friend? Where did you meet them?",
    "A portal to another world opens in front of you. You don't know how long it will stay open or if you'll be able to get back after you go through. What do you do?",
    "Cobblers",
    "What book has changed one of your long-held opinions?",
    "Jewelry",
    "What is the fanciest restaurant you have eaten at?",
    "Who is someone popular now that you really like? Why do you like them so much?",
    "Olympic Games",
    "Napoleon",
    "Zebras",
    "Do you have any siblings?",
    "Archery",
    "What problems will technology solve in the next 5 years? What problems will it create?",
    "Apes",
    "Vaccines",
    "What do you hope to achieve in your professional life?",
    "If you opened a restaurant, what kind of food would you serve?",
    "Oil",
    "Toads",
    "Farmers Markets",
    "Cocoa",
    "Muppets",
    "If you were a book, what would the title be?",
    "Can you think of any technology that has only made the world worse? How about a piece of technology that has only made the world better?",
    "What is the most useful app on your phone?",
    "Do you like reality TV shows? Why or why not? If so, which ones?",
    "What benefit do you bring to the group when you hang out with friends?",
    "Hunting",
    "What do you do for a living?",
    "What's your favorite way to get exercise?",
    "What was the best period of your life so far? What do you think will be the best period of your entire life?",
    "Gold",
    "What do you think about reality TV? Why do you think it's so popular?",
    "Turtles",
    "What is the most overrated movie?",
    "Did your family take seasonal vacations?",
    "Tennis",
    "Milk",
    "Insects",
    "What did you do this past weekend?",
    "How often do you help others? Who do you help? How do you help?",
    "Salvation Army",
    "Do you wish there were more or fewer holidays? Why?",
    "Sharks",
    "Disney Movies",
    "Prisons",
    "How can governments make education more efficient?",
    "Do you prefer summer or winter activities?",
    "What is the most disgusting thing you have heard happened at a restaurant?",
    "Which TV show do you want your life to be like?",
    "Bridges",
    "What was (is) your least favorite subject?",
    "What smell brings back great memories?",
    "What's your favorite way to decompress from a long day at work?",
    "Frogs",
    "What were you really into when you were a kid?",
    "Do you play in any fantasy sports leagues? If so, how into fantasy sports are you?",
    "Where was the last place you went on vacation?",
    "What's the best show currently on TV?",
    "What is the longest book you've read?",
    "Masonry",
    "Books",
    "What is something that you have gotten in trouble for at school/work?",
    "What album would you listen to on repeat?",
    "Do you like documentaries? Why / why not?",
    "What do you think the next big technological advance will be?",
    "If you didn't care at all what people thought of you, what clothes would you wear?",
    "Murderers",
    "Cigarettes",
    "Do you like classical music?",
    "Do you usually achieve the goals you set? Why or why not?",
    "What is the most disgusting habit some people have?",
    "Do you prefer to watch movies in the theater or in the comfort of your own home?",
    "Bakeries",
    "Do you think people read more or fewer books now than 50 years ago?",
    "What is the strangest themed restaurant you have heard of?",
    "What was your worst vacation experience?",
    "Elephants",
    "Sugar",
    "If you could meet anyone in history, who would it be?",
    "What is the strangest dream you have ever had?",
    "Railroads",
    "What do you think of standardized tests?",
    "Snakes",
    "Pilots",
    "Where do you spend most of your free time/day?",
    "Stadiums",
    "Socialism",
    "What's the worst job interview you've ever had?",
    "How should success be measured? And by that measurement, who is the most successful person you know?",
    "What's the best / worst thing about your work/school?",
    "What is the most annoying habit someone can have?",
    "Do you prefer short hair or long hair on a guy/girl?",
    "What sports do you like to watch?",
    "What flavor of ice cream do you wish existed?",
    "Army",
    "What food do you know you shouldn't eat but can't stop yourself?",
    "What is the best pair of shoes you have ever owned? Why were they so good?",
    "Does having a day off for a holiday increase or decrease productivity at work?",
    "What would be your perfect weekend?",
    "Mountaineering",
    "Bread",
    "Games",
    "Sewing Machines",
    "Buddhism",
    "Hammocks",
    "Crocodiles",
    "Boats",
    "What book has influenced you the most?",
    "Money",
    "Alligators",
    "Fishing",
    "Do you have any pets? What are their names?",
    "If you could make a holiday, what would it be like? What traditions would it have? What would people eat on your holiday?",
    "Who was your best friend in elementary school?",
    "Giraffes",
    "Camels",
    "Would you advise someone to attend a university now that you've completed your education?",
    "Pottery",
    "What's the best way to discover new music?",
    "What was the last book you read?",
    "What is your favorite day of the week?",
    "What is your favorite movie soundtrack?",
    "What did you do on your last vacation?",
    "What technology from a science fiction movie would you most like to have?",
    "Police",
    "Who had the biggest impact on the person you have become?",
    "What is your favorite holiday?",
    "Baseball",
    "What's your favorite way to waste time?",
    "Royalty",
    "Disasters",
    "If some of the lesser-known holidays were commercialized, what would the commercialization look like?",
    "Do you play any instruments?",
    "Vegetables",
    "Tattoos",
    "Mummies",
    "What do you do when you hang out with your friends?",
    "What are some goals you have already achieved?",
    "If you could learn the answer to one question about your future, what would the question be?",
    "How have your goals changed over your life?",
    "If your life was a meal, what would kind of meal would it be?",
    "Who do you think has the biggest impact on fashion trends: actors and actresses, musicians, fashion designers, or consumers?",
    "Death",
    "What kind of case do you have for your phone? Why did you choose it?",
    "What is the most embarrassing piece of clothing you own?",
    "What are the three best apps on your phone?",
    "Sailing",
    "Central America",
    "What's the best sitcom past or present?",
    "Boxing",
    "What was the best invention of the last 50 years?",
    "Who was the last person you called?",
    "What song always puts you in a good mood?",
    "What do you wish your phone could do?",
    "Who is your favorite entertainer (comedian, musician, actor, etc.)?",
    "Athletics",
    "What defines a sport? Is fishing a sport? How about video game tournaments?",
    "Where is the worst place you have been stuck for a long time?",
    "Where did you go on your last vacation?",
    "Caves",
    "Which is more important, having a great car or a great house? Why?",
    "Which emerging technology are you most excited about?",
    "If you could bring back one TV show that was canceled, which one would you bring back?",
    "What's the best pet name you can come up with for a specific type of pet? (Like theseÂ orange cat names.)",
    "Is it better to live where there are four seasons or where one season takes up most of the year?",
    "Golf",
    "Banana",
    "Who is the funniest person you've met?",
    "What's the worst movie you have seen recently?",
    "Will technology save the human race or destroy it?",
    "Which do you prefer, popular music or relatively unknown music?",
    "Red Cross",
    "Have you ever been in love?",
    "Bears",
    "Motherhood",
    "If you had intro music, what song would it be? Why?",
    "What old trend is coming back these days?",
    "What holidays have been over-commercialized?",
    "What makes you nervous?",
    "Where is the most relaxing place you have been?",
    "Zeppelins",
    "What is your middle name?",
    "What is the craziest, most outrageous thing you want to achieve?",
    "Birds",
    "What is your favorite song of all time?",
    "If you were in the Olympics, what sport would you play?",
    "Slavery",
    "If you were a king/queen, what would your throne look like?",
    "Do you text more or call more? Why?",
    "How do you plan to make the world a better place?",
    "What piece of technology is really frustrating to use?",
    "When you describe yourself to others, what words do you use?",
    "Do you prefer traveling alone or with a group?",
    "If you could have any animal as a pet, what animal would you choose?",
    "What is the first thing you do when you wake up?",
    "Water Skiing",
    "How often do you exercise?",
    "Earthquake",
    "Fencing",
    "Gymnastics",
    "Skating",
    "What are some goals you have failed to accomplish?",
    "Chess",
    "Wood",
    "Pineapple",
    "What's the most refreshing thing on a hot summer day?",
    "Where is the nicest place you have been to in fall?",
    "Basketball",
    "What's your favorite genre of movie?",
    "Do you know what your your name means?",
    "Pigs",
    "What is the longest plane trip you have taken?",
    "How often do you curse? And what's your go-to string of curse words?",
    "Which do you prefer? Books or movies?",
    "How has the education you received changed your life?",
    "Magicians",
    "Are bigger or smaller schools better?",
    "What are some things that you should not say during a job interview?",
    "What was the last funny video you saw?",
    "Tobacco",
    "Has anyone ever saved your life?",
    "Breweries",
    "Rhinoceros",
    "What countries have you traveled to?",
    "Cats",
    "Why do you think sports are common across almost all cultures present and past?",
    "Lighthouses",
    "What's your favorite season? Why?",
    "Do you always have to have the latest phone?",
    "Windmills",
    "What is your first childhood memory?",
    "Pipes",
    "Spiritism",
    "What is the strangest app you have heard of or tried?",
    "Do you prefer fiction or nonfiction books?",
    "How has technology changed the music industry?",
    "Have your parents influenced what goals you have?",
    "Where is the most beautiful place near where you live?",
    "Do athletes deserve the high salaries they receive? Why or why not?",
    "Balloons",
    "What are some strange beliefs that some people have?",
    "Were you the class clown or teacher's pet?",
    "What are some things you want to accomplish before you die?",
    "WhichÂ recent news storyÂ is the most interesting?",
    "Vanilla",
    "Boy Scouts",
    "What is the best job interview you've ever had?",
    "What are your turn offs?",
    "What's the worst fast food restaurant?",
    "Are you a very organized person?",
    "What three words best describe you?",
    "Which season are you most active in?",
    "What was (is) your favorite subject?",
    "How many apps do you have on your phone?",
    "Blacksmiths",
    "What do you think of buffets?",
    "What's the most addictive mobile game you have played?",
    "What do you like to do in the spring?",
    "Does fashion help society in any way?",
    "Pharmacy",
    "Puppets",
    "What movie scene choked you up the most?",
    "Skull",
    "What's your favorite food?",
    "Cows",
    "What is the silliest fear you have?",
    "Would you rather be rich and never find true love or be poor and find true love?",
    "Dance",
    "What is your favorite cuisine or type of food?",
    "What is the most annoying thing about your phone?",
    "What's your favorite thing about our office?",
    "Where is the most awe-inspiring place you have been?",
    "How do you think traveling to a lot of different countries changes a person?",
    "Rice",
    "Cemetery",
    "If you had 10 million dollars, would you still be working/going to school?",
    "What do you know about the history of some holidays?",
    "What's the first thing you do after school/work?",
    "What was your favorite restaurant when you were a child?",
    "Gypsies",
    "Sports",
    "Cricket",
    "Asia",
    "What's the funniest TV series you have seen?",
    "Playing Cards",
    "What animal or insect do you wish humans could eradicate?",
    "What is something popular now that annoys you?",
    "Are you very active, or do you prefer to just relax in your free time?",
    "Matches",
    "What was the most overhyped place you've traveled to?",
    "Which app has helped society the most? Which one has hurt society the most?",
    "The world has become infested with rabid dogs with the intelligence of a 5-year-old, where do you hole up to survive the â€œa-pup-calypseâ€?",
    "What do you think of online education?",
    "What do you do when you're bored?",
    "How have TV shows changed over the years?",
    "What does your own personal hell look like? How about your own personal heaven?",
    "Donkeys",
    "What would you want your last meal to be if you were on death row?",
    "When people make mistakes about food (especially foreign food), do you feel the need to correct them? (i.e.Â sushi / sashimiÂ orÂ stromboli / calzone)",
    "Native Americans",
    "If you had to change your name, what would your new name be?",
    "Shells",
    "Hockey",
    "What kinds of food do you usually eat on your favorite holiday?",
    "Bats",
    "Firemen",
    "What is the first think you notice about a guy or girl?",
    "What do you fear is hiding in the dark?",
    "Which do you prefer, fall or spring?",
    "Meteorology",
    "What is your favorite shirt?",
    "Pipe Organs",
    "Beekeeping",
    "What book has had the biggest effect on the modern world?",
    "What food looks disgusting but tastes delicious?",
    "Where and when was the most amazing sunset you have ever seen?",
    "Billiards",
    "Whatâ€™s your favorite way to waste time?",
    "Music",
    "Do movies have the same power as books to change the world?",
    "You have to relive one day of your life forever. Which day do you choose?",
    "When was the last time you worked incredibly hard?",
    "Do you have any pets?",
    "What is your favorite holiday?",
    "Would you eat at a restaurant that was really dirty if the food was amazing?",
    "Funerals",
    "Cheese",
    "Canoes",
    "What is your least favorite food?",
    "What bands or types of music do you listen to when you exercise?",
    "What is the worst hotel you have stayed at? How about the best hotel?",
    "Records, tapes, CDs, MP3s, streaming. Which did you grow up with? What is good and bad about each?",
  ];

  static getRandomTopics(int count) {
    List<String> results = [];
    for (int i = 0; i < count; i++) {
      results.add(topics[Random().nextInt(topics.length)]);
    }
    return results;
  }
}
